# Site settings
title: Zoeland
email: your-email@domain.com
description: >
  Zoeland items
baseurl: "/zoeland"
url: "https://elena-zoe.github.io/zoeland/"

# Collections
#collections:
#  books:
#    output: false

sass:
  style: compressed
